title: Hello World   
layout: post
categories: [Hello, World]
tags: [hello, world]
image: /assets/img/helloworld.jpg
gif: mygif (Only write the name of the file. No extension. The files needs to be in "/assets/gif")
description: "Say hello to the world!"
customexcerpt: "Custom excerpt for the homepage"
remote_theme: PandaSekh/Jekyll-YAMT
